titleOnly: true
allowMergeCommits: false
allowRevertCommits: false
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - repo
  - wip
  - merge